# Generated by Django 3.2.16 on 2023-08-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0020_alter_claim_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackprompt',
            name='phone_number',
            field=models.CharField(db_column='PhoneNumber', max_length=36),
        ),
    ]
