# Generated by Django 3.2.16 on 2023-08-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0020_alter_claim_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='visit_type_out_in_patient',
            field=models.CharField(blank=True, db_column='ClaimTypeOutIn', max_length=4, null=True),
        )
    ]
