# Generated by Django 4.2.15 on 2024-08-20 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0018_auto_20230925_2243'),
        ('claim', '0030_merge_20240318_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='pre_authorization',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),

    ]
