# Generated by Django 4.2.15 on 2024-08-20 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0018_auto_20230925_2243'),
        ('claim', '0030_merge_20240318_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='care_type',
            field=models.CharField(
                blank=True, db_column='CareType', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='pre_authorization',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='refer_from',
            field=models.ForeignKey(blank=True, db_column='ReferFrom', null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='referFromHF', to='location.healthfacility'),
        ),
        migrations.AddField(
            model_name='claim',
            name='refer_to',
            field=models.ForeignKey(blank=True, db_column='ReferTo', null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='referToHF', to='location.healthfacility'),
        ),
    ]
