# Generated by Django 4.2.10 on 2024-09-04 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("policy", "0009_auto_20240716_1744"),
        ("claim", "0031_claim_care_type_claim_pre_authorization_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claimdedrem",
            name="policy",
            field=models.ForeignKey(
                db_column="PolicyID",
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="claim_ded_rems",
                to="policy.policy",
            ),
            preserve_default=False,
        ),
    ]
