# Generated by Django 4.2.13 on 2024-10-04 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0032_alter_claimdedrem_policy'),
        ('claim', '0034_claim_care_type_claim_refer_from_claim_refer_to_and_more'),
    ]

    operations = [
    ]
